from __future__ import annotations

from pathlib import Path
from typing import Any

from openamp_foundry.config import load_config
from openamp_foundry.data.loaders import is_valid_sequence, load_candidates_csv
from openamp_foundry.evidence.certificate import build_certificate
from openamp_foundry.features.physchem import compute_features
from openamp_foundry.scoring.activity import activity_likeness_score
from openamp_foundry.scoring.ensemble import ensemble_score, known_failure_modes, selection_reasons
from openamp_foundry.scoring.novelty import novelty_score
from openamp_foundry.scoring.safety import safety_score
from openamp_foundry.scoring.synthesis import synthesis_feasibility_score
from openamp_foundry.selection.diversity import greedy_diverse_select
from openamp_foundry.selection.pareto import rank_candidates
from openamp_foundry.types import ScoredCandidate
from openamp_foundry.utils.io import write_json, write_jsonl


def score_candidates(
    candidate_path: str | Path,
    reference_path: str | Path | None = None,
    config_path: str | Path = "configs/pipeline.yaml",
) -> tuple[list[ScoredCandidate], dict[str, Any]]:
    config = load_config(config_path)
    allowed = set(config["filters"]["allowed_amino_acids"])
    candidates = load_candidates_csv(candidate_path)
    references = load_candidates_csv(reference_path) if reference_path else []
    weights = config["weights"]

    scored: list[ScoredCandidate] = []
    for candidate in candidates:
        valid = is_valid_sequence(candidate.sequence, allowed=allowed)
        features = compute_features(candidate.sequence)
        act = activity_likeness_score(features) if valid else 0.0
        safe = safety_score(features) if valid else 0.0
        synth = synthesis_feasibility_score(features, valid_sequence=valid)
        nov, nearest = novelty_score(candidate.sequence, references)
        raw_scores = {
            "activity": act,
            "safety": safe,
            "synthesis": synth,
            "novelty": nov,
        }
        raw_scores["ensemble"] = ensemble_score(raw_scores, weights)
        item = ScoredCandidate(
            candidate=candidate,
            features=features,
            scores=raw_scores,
            references_checked=[str(reference_path)] if reference_path else [],
            nearest_reference=nearest,
        )
        item.selection_reason = selection_reasons(raw_scores)
        item.known_failure_modes = known_failure_modes(raw_scores)
        scored.append(item)
    return scored, config


def run_ranking_pipeline(
    candidate_path: str | Path,
    reference_path: str | Path | None,
    out_path: str | Path,
    report_path: str | Path | None = None,
    cert_dir: str | Path | None = None,
    config_path: str | Path = "configs/pipeline.yaml",
) -> list[ScoredCandidate]:
    scored, config = score_candidates(candidate_path, reference_path, config_path)
    ranked = rank_candidates(scored)
    top_n = int(config.get("selection", {}).get("top_n", len(ranked)))
    selected = greedy_diverse_select(ranked, top_n=top_n)

    rows = []
    for item in ranked:
        rows.append(
            {
                "candidate_id": item.candidate.candidate_id,
                "sequence": item.candidate.sequence,
                "source": item.candidate.source,
                "scores": item.scores,
                "features": item.features,
                "nearest_reference": item.nearest_reference,
                "selection_reason": item.selection_reason,
                "known_failure_modes": item.known_failure_modes,
            }
        )
    write_jsonl(out_path, rows)

    if cert_dir:
        cert_root = Path(cert_dir)
        for item in selected:
            cert = build_certificate(item, config, [str(reference_path)] if reference_path else [])
            write_json(cert_root / f"{item.candidate.candidate_id}.json", cert)

    if report_path:
        write_report(report_path, ranked, selected)

    return ranked


def write_report(
    path: str | Path, ranked: list[ScoredCandidate], selected: list[ScoredCandidate]
) -> None:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# OpenAMP Foundry Demo Report",
        "",
        "This report is generated by transparent baseline heuristics.",
        "It does not prove antimicrobial activity.",
        "",
        f"Total candidates scored: {len(ranked)}",
        f"Candidates selected for evidence certificates: {len(selected)}",
        "",
        "| Rank | ID | Sequence | Ensemble | Activity | Safety | Synthesis | Novelty |",
        "|---:|---|---|---:|---:|---:|---:|---:|",
    ]
    for idx, item in enumerate(ranked, start=1):
        s = item.scores
        lines.append(
            f"| {idx} | {item.candidate.candidate_id} | `{item.candidate.sequence}` | "
            f"{s['ensemble']:.4f} | {s['activity']:.4f} | {s['safety']:.4f} | "
            f"{s['synthesis']:.4f} | {s['novelty']:.4f} |"
        )
    p.write_text("\n".join(lines) + "\n", encoding="utf-8")
