"""Quality control commands."""
from __future__ import annotations
import argparse
import json
from pathlib import Path
from datetime import datetime, timezone

def _run_synthesis_order(args: argparse.Namespace) -> int:
    import csv as _csv
    from openamp_foundry.features.physchem import compute_features
    from openamp_foundry.qc.order_generator import (
        generate_synthesis_order,
        write_order_csv,
        write_synthesis_checklist,
    )

    panel_path = Path(args.panel_csv)
    if not panel_path.exists():
        print(json.dumps({"status": "error", "message": f"File not found: {args.panel_csv}"}))
        return 1

    panel = []
    with open(panel_path, newline="", encoding="utf-8") as f:
        reader = _csv.DictReader(f)
        required_cols = {"candidate_id", "sequence"}
        if not required_cols.issubset(set(reader.fieldnames or [])):
            missing = required_cols - set(reader.fieldnames or [])
            print(json.dumps({
                "status": "error",
                "message": f"Panel CSV missing required columns: {sorted(missing)}",
                "found_columns": list(reader.fieldnames or []),
            }))
            return 1
        for row in reader:
            panel.append(row)

    mu_h_map = {}
    for row in panel:
        seq = row["sequence"].strip().upper()
        feats = compute_features(seq)
        mu_h_map[row["candidate_id"]] = feats.get("hydrophobic_moment", 0.0)

    qty = args.quantity_mg
    order_rows, qc_results = generate_synthesis_order(
        panel,
        mu_h_map=mu_h_map,
        default_quantity_mg=qty,
        high_difficulty_quantity_mg=qty * 2,
    )

    generated_at = datetime.now(timezone.utc).isoformat()
    write_order_csv(order_rows, args.out_csv)
    write_synthesis_checklist(
        order_rows,
        qc_results,
        args.out_md,
        generated_at=generated_at,
        panel_csv=args.panel_csv,
    )

    n_acetyl = sum(1 for r in order_rows if r["n_modification"] == "Ac-")
    n_amide = sum(1 for r in order_rows if r["c_modification"] == "NH2")
    n_high = sum(1 for r in order_rows if r["synthesis_difficulty"] == "HIGH")
    total_mg = sum(float(r["quantity_mg"]) for r in order_rows)

    print(json.dumps({
        "status": "ok",
        "n_candidates": len(order_rows),
        "n_n_terminal_acetylation": n_acetyl,
        "n_c_terminal_amide": n_amide,
        "n_high_difficulty": n_high,
        "total_quantity_mg": total_mg,
        "out_csv": args.out_csv,
        "out_md": args.out_md,
        "disclaimer": (
            "This order is computationally generated. Human expert review required "
            "before submitting to vendor. No antimicrobial activity has been demonstrated."
        ),
    }, indent=2))
    return 0


def _run_presynth_qc(args: argparse.Namespace) -> int:
    import csv as _csv
    from openamp_foundry.qc.presynth_check import check_panel
    from openamp_foundry.features.physchem import compute_features

    panel = []
    with open(args.panel_csv, newline="", encoding="utf-8") as f:
        for row in _csv.DictReader(f):
            panel.append(row)

    mu_h_map = {}
    for row in panel:
        seq = row["sequence"].strip().upper()
        feats = compute_features(seq)
        mu_h_map[row["candidate_id"]] = feats.get("hydrophobic_moment", 0.0)

    results = check_panel(panel, mu_h_map=mu_h_map)
    generated_at = datetime.now(timezone.utc).isoformat()

    lines = [
        "# Pre-Synthesis QC Report",
        "",
        "> Generated by `make presynth-qc`. Review all FLAGS before ordering synthesis.",
        "",
        f"Generated: {generated_at}  ",
        f"Panel: {args.panel_csv}  ",
        f"Candidates checked: {len(results)}",
        "",
        "## Summary Table",
        "",
        "| # | ID | Seq | MW(Da) | pI | Charge pH7.4 | M | C | OxRisk | Agg | TrypSites | SPPS | UV |",
        "|--:|---|---|---:|---:|---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|",
    ]

    for i, r in enumerate(results, 1):
        lines.append(
            f"| {i} | {r.candidate_id} | `{r.sequence}` | {r.molecular_weight_da} | {r.isoelectric_point} "
            f"| {r.charge_ph74:.1f} | {r.methionine_count} | {r.cysteine_count} "
            f"| {'⚠' if r.has_oxidation_risk else '✓'} "
            f"| {'⚠' if r.aggregation_risk else '✓'} "
            f"| {len(r.trypsin_sites)} "
            f"| {r.synthesis_difficulty} "
            f"| {'Y' if r.has_uv_chromophore else 'N (BCA)'} |"
        )

    lines += ["", "## Per-Candidate Details", ""]
    for r in results:
        lines += [
            f"### {r.candidate_id} — `{r.sequence}`",
            "",
            f"- **MW:** {r.molecular_weight_da} Da  | **pI:** {r.isoelectric_point}",
            f"- **Charge:** pH 7.4 = {r.charge_ph74:.2f} | pH 6.0 = {r.charge_ph60:.2f}",
            f"- **Methionine:** {r.methionine_count} | **Cysteine:** {r.cysteine_count}",
            f"- **Aggregation risk:** {'YES — ' + r.hydrophobic_run if r.aggregation_risk else 'No'}",
            f"- **Trypsin cleavage sites (interior):** {r.trypsin_sites if r.trypsin_sites else 'None'}",
            f"- **Chymotrypsin sites:** {r.chymotrypsin_sites if r.chymotrypsin_sites else 'None'}",
            f"- **Deamidation hotspots:** {r.deamidation_sites if r.deamidation_sites else 'None'}",
            f"- **Concentration method:** {r.formulation_note}",
            f"- **Hemolysis start conc:** {r.hemolysis_start_conc}",
            f"- **SPPS difficulty:** {r.synthesis_difficulty}",
        ]
        if r.flags:
            lines.append("- **FLAGS:**")
            for flag in r.flags:
                lines.append(f"  - ⚠ {flag}")
        else:
            lines.append("- **FLAGS:** None")
        lines.append("")

    lines += [
        "## Formulation Protocol (Universal)",
        "",
        "1. Dissolve lyophilised peptide in sterile ultrapure water to 1–5 mM stock",
        "2. If poor solubility: add 10% DMSO; vortex; bath-sonicate 5 min",
        "3. Dilute to working stock (100 μM) in 10 mM sodium phosphate pH 7.0",
        "4. Filter through 0.22 μm syringe filter (sterile)",
        "5. Determine concentration: A280 (if W/Y present) or BCA assay",
        "6. Aliquot 10–20 μL; store −80°C; avoid freeze-thaw cycles",
        "7. Freshly dilute into MIC assay medium (MHB, RPMI) immediately before use",
        "",
        "## Hemolysis Assay Starting Concentrations",
        "",
        "| μH range | Risk level | Starting concentration |",
        "|---|---|---|",
        "| > 0.80 | HIGH | ≤ MIC/10 |",
        "| 0.55 – 0.80 | MODERATE | ≤ MIC/3 |",
        "| < 0.55 | LOW | MIC |",
        "",
        "Use 0.5% (v/v) human RBCs in PBS. Positive control: 1% Triton X-100. "
        "Negative control: PBS only. Read OD541 after 1h at 37°C.",
        "",
        "## Disclaimer",
        "",
        "These QC checks are computational. Actual synthesis difficulty and yield depend "
        "on the synthesis laboratory's protocols, resin choice, and coupling chemistry. "
        "Verify purity by HPLC-MS before assay.",
    ]

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")

    n_flags = sum(1 for r in results if r.flags)
    n_ox = sum(1 for r in results if r.has_oxidation_risk)
    print(json.dumps({
        "status": "ok",
        "n_candidates": len(results),
        "n_with_flags": n_flags,
        "n_oxidation_risk": n_ox,
        "out": args.out,
    }, indent=2))
    return 0


