"""Assemble a sponsor / wet-lab-collaborator packet from the validated candidates.

Selects a diverse final panel from the strongest-consensus pool (3/3 general AMP tools
+ AMPActiPred ABP+ + HemoFinder non-hemolytic + Non-AntiCP), generates a synthesis-ready
order table (modifications, MW, purity, quantity) via the pre-synthesis QC, and writes a
one-page cover + assembles the evidence into handoff/sponsor_packet/.

Usage:
    .venv/bin/python3 scripts/build_sponsor_packet.py [--panel 12]
"""
from __future__ import annotations

import argparse
import csv
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
import sys
sys.path.insert(0, str(ROOT / "src"))
from openamp_foundry.qc.presynth_check import check_sequence

VDIR = ROOT / "outputs" / "external_validation"
MASTER = ROOT / "outputs" / "expert_1000_candidates.csv"
OUT = ROOT / "handoff" / "sponsor_packet"

T = lambda v: str(v).strip().lower() in ("true", "1", "yes")


def select_panel(n: int) -> list[dict]:
    matrix = {r["candidate_id"]: r for r in csv.DictReader(open(VDIR / "consensus_matrix.csv"))}
    master = {r["candidate_id"]: r for r in csv.DictReader(open(MASTER))}
    rec = [r["candidate_id"] for r in csv.DictReader(open(VDIR / "recommended_shortlist.csv"))]

    def gen3(c):  # all three general AMP tools positive
        m = matrix[c]
        return T(m["camp4_amp"]) and T(m["ampscanner_amp"]) and T(m["macrel_amp"])

    strong = [c for c in rec if gen3(c)]
    strong.sort(key=lambda c: -float(master[c]["final_score"]))

    # Greedy scaffold diversity: spread across length × charge bins; prefer hinged.
    picked, seen_bins = [], set()
    for prefer_hinge in (True, False):
        for c in strong:
            if len(picked) >= n:
                break
            if c in picked:
                continue
            if prefer_hinge and not T(master[c]["has_central_hinge"]):
                continue
            m = master[c]
            b = (len(m["sequence"]) // 4, round(float(m["net_charge_ph74"])))
            if b in seen_bins and len(picked) < n - 2:
                continue
            seen_bins.add(b)
            picked.append(c)
    # top-up if diversity left us short
    for c in strong:
        if len(picked) >= n:
            break
        if c not in picked:
            picked.append(c)
    return [master[c] for c in picked[:n]]


def order_row(r: dict) -> dict:
    qc = check_sequence(r["candidate_id"], r["sequence"], mu_h=float(r["mu_h"]))
    return {
        "candidate_id": r["candidate_id"],
        "sequence": r["sequence"],
        "length": qc.length,
        "MW_Da": qc.molecular_weight_da,
        "net_charge_pH7.4": round(qc.charge_ph74, 1),
        "pI": qc.isoelectric_point,
        "N_terminus": "Acetyl (Ac-)" if qc.n_acetylation_recommended else "Free",
        "C_terminus": "Amide (-NH2)" if qc.c_amidation_recommended else "Free acid (-OH)",
        "purity": ">=95% (HPLC)",
        "quantity": "5 mg",
        "counter_ion": "acetate (TFA-free)",
        "special_handling": "; ".join(
            f for f in qc.flags if any(k in f for k in
            ("HYDROPHOBIC_RUN", "TRP_PHOTOLABILITY", "DEAMIDATION", "ISOMERIZATION"))
        ) or "none",
        "internal_final": r["final_score"],
    }


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--panel", type=int, default=12)
    args = ap.parse_args()

    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "evidence").mkdir(exist_ok=True)

    panel = select_panel(args.panel)
    orders = [order_row(r) for r in panel]

    # 1. Synthesis order table (the thing the vendor/lab needs)
    with open(OUT / "01_synthesis_order_table.csv", "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(orders[0].keys()))
        w.writeheader(); w.writerows(orders)

    # 2. Panel FASTA
    with open(OUT / "02_panel.fasta", "w") as f:
        for o in orders:
            f.write(f">{o['candidate_id']} len={o['length']} charge={o['net_charge_pH7.4']} "
                    f"Nterm={o['N_terminus']} Cterm={o['C_terminus']}\n{o['sequence']}\n")

    # 3. Cover / executive summary
    n = len(panel)
    cover = OUT / "00_COVER_executive_summary.md"
    cover.write_text(f"""# OpenAMP Foundry — Candidate Antimicrobial Peptides for Wet-Lab Validation

**Prepared for:** prospective wet-lab collaborator / sponsor
**Panel:** {n} de-novo antimicrobial peptide (AMP) candidates, synthesis-ready
**Date:** 2026-06-30

## The ask

We are seeking a wet-lab collaborator (or sponsorship of CRO synthesis + assays) to
experimentally validate {n} computationally-designed antimicrobial peptide candidates.
Estimated cost is modest: ~{n} peptides at >=95% purity (~5 mg each) plus a standard
MIC / hemolysis / cytotoxicity panel. We provide the full computational evidence trail;
you provide (or we jointly fund) the bench validation. Data and authorship shared.

## What these are

De-novo peptides generated by an open, reproducible, safety-first pipeline — NOT mined
from databases. Each candidate is, by construction and by independent confirmation:

- **Novel** — <40% identity to all 51,503 known AMPs (APD6 + DRAMP 3.0 + UniProt +
  ESCAPE + dbAMP 3.0 + DBAASP), and no contiguous motif lifted from a known AMP.
- **Predicted antimicrobial by 4 independent external tools** — CAMP-R4, AMP Scanner v2,
  Macrel, and AMPActiPred (antibacterial-specific). The full panel here is positive on
  all general AMP tools AND AMPActiPred ABP+.
- **Predicted low-hemolysis** — HemoFinder non-hemolytic; designed with a selectivity
  window (cationic, controlled hydrophobicity, central helix-hinge motif).
- **Predicted low off-target activity** — AntiCP2 Non-AntiCP.
- **Synthesisable** — short, no Cys/Met, no aggregation/aspartimide liabilities.

## Headline validation numbers (450-candidate batch)

- 447 / 450 AMP-positive on >=2 independent external predictors.
- 225 / 450 antibacterial-priority (ABP+ AND non-hemolytic AND Non-AntiCP AND >=2 AMP tools).
- This panel is the top {n} of the strongest-consensus subset (all general AMP tools +
  antibacterial-specific + non-hemolytic + non-off-target), chosen for scaffold diversity.

## Honest limitations (please read)

- **All results are computational predictions, not measured activity.** The purpose of
  this collaboration is precisely to test them at the bench.
- **Novelty is computational** (sequence/motif vs AMP databases). A global BLASTp (NCBI nr)
  and a formal patent/freedom-to-operate search are recommended before any filing and have
  not been completed for this batch.
- No claim of efficacy or safety is made. Standard biosafety practice applies.

## What is in this packet

| File | Contents |
|------|----------|
| `00_COVER_executive_summary.md` | this page |
| `01_synthesis_order_table.csv` | synthesis-ready specs (sequence, mods, MW, purity, qty) |
| `02_panel.fasta` | the {n} candidate sequences |
| `03_proposed_assay_plan.md` | recommended MIC / hemolysis / cytotoxicity protocol |
| `evidence/consensus_report.md` | full 6-tool external-predictor consensus |
| `evidence/consensus_matrix.csv` | per-candidate, per-tool calls (all 450) |
| `evidence/pipeline_diagrams.md` | how the candidates were generated + filtered |
| `evidence/novelty_audit_guide.md` | novelty methodology + database provenance |

## Contact

[your name / institution / email]
""")

    # 4. Proposed assay plan
    (OUT / "03_proposed_assay_plan.md").write_text("""# Proposed Assay Plan

A minimal, standard validation panel for the candidate peptides.

## 1. Antibacterial activity — MIC (broth microdilution, CLSI M07)
Test strains (suggested, drug-resistant priority pathogens):
- *Escherichia coli* ATCC 25922 (Gram-negative reference)
- *Pseudomonas aeruginosa* ATCC 27853
- *Klebsiella pneumoniae* (carbapenem-resistant clinical isolate if available)
- *Staphylococcus aureus* ATCC 29213 + an MRSA isolate
- *Acinetobacter baumannii* (MDR isolate if available)

Controls: a known AMP (e.g. LL-37 or melittin) and a standard antibiotic.
Readout: MIC (µg/mL) in Mueller-Hinton broth. Run a parallel RPMI-1640 + 10% LB plate
for any proline-rich candidates (intracellular mechanism — flagged in the order table).

## 2. Hemolysis — HC50 vs human red blood cells
Serial dilution vs fresh hRBCs; readout = % hemolysis (A405) → HC50.
Compute the therapeutic index (HC50 / MIC). Melittin = hemolytic positive control.

## 3. Mammalian cytotoxicity — MTS/MTT
HEK293 or HepG2 viability across the MIC–10×MIC range.

## Synthesis notes
All peptides: N-terminal acetylation and/or C-terminal amidation as specified in
`01_synthesis_order_table.csv` (blocks exopeptidase / boosts stability — zero extra cost).
>=95% HPLC purity, TFA-free (acetate) counter-ion, ~5 mg each. Confirm identity by MS.
""")

    # 5. Copy evidence
    for src, dst in [
        (VDIR / "consensus_report.md", "consensus_report.md"),
        (VDIR / "consensus_matrix.csv", "consensus_matrix.csv"),
        (ROOT / "docs" / "diagrams.md", "pipeline_diagrams.md"),
        (ROOT / "docs" / "NOVELTY_AUDIT_GUIDE.md", "novelty_audit_guide.md"),
    ]:
        if src.exists():
            shutil.copy(src, OUT / "evidence" / dst)

    print(f"Sponsor packet → {OUT}/  ({n} candidates)")
    for o in orders:
        print(f"  {o['candidate_id']}  {o['sequence']:26} {o['N_terminus']:14} {o['C_terminus']:16} final={o['internal_final']}")
    print(f"\nFiles:")
    for p in sorted(OUT.rglob("*")):
        if p.is_file():
            print(f"  {p.relative_to(OUT)}")


if __name__ == "__main__":
    main()
