#!/usr/bin/env python3
"""CLI script that generates a skeleton external review packet JSON.

Usage:
    python scripts/generate_review_packet.py \\
        --pipeline-version VERSION \\
        --git-sha SHA \\
        --candidate-count N \\
        --proof-ladder-level LEVEL \\
        --out OUTPUT.json \\
        [--validate]

The output is a valid skeleton (empty candidates list, placeholder benchmark
and calibration summaries, dry_lab_only_attestation=true) that validates
against schemas/external_review_packet.schema.json.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def build_skeleton(
    pipeline_version: str,
    git_sha: str,
    candidate_count: int,
    proof_ladder_level: int,
) -> dict[str, Any]:
    """Build a skeleton external review packet dict."""
    now = datetime.now(timezone.utc)
    candidates = []
    if candidate_count > 0:
        for i in range(candidate_count):
            candidates.append({
                "candidate_id": f"PLACEHOLDER_CAND-{i + 1:03d}",
                "sequence": "KLAKLAKKLAKLAK",
                "ensemble_score": 0.5,
                "proof_ladder_level": 1,
                "family": "PLACEHOLDER",
                "selection_rationale": "PLACEHOLDER — update with actual selection rationale",
                "safety_notes": "PLACEHOLDER — update with actual safety notes",
            })
    return {
        "packet_id": f"ERP-{now.strftime('%Y-%m-%d')}-SKELETON",
        "version": "1.0.0",
        "generated_at": now.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "pipeline_version": pipeline_version,
        "git_sha": git_sha,
        "candidate_count": candidate_count,
        "candidates": candidates,
        "benchmark_summary": {
            "auroc": 0.0,
            "benchmark_name": "PLACEHOLDER — update with actual benchmark results",
            "n_positives": 0,
            "n_negatives": 0,
        },
        "calibration_summary": {
            "brier_score": 0.0,
            "calibration_slope": 0.0,
            "calibration_assessment": "uninformative",
        },
        "limitations": [
            "Computational outputs are hypotheses and review aids. They are not biological proof.",
            "Skeleton packet — candidate data, benchmark results, and safety attestations are placeholders.",
        ],
        "safety_attestations": {
            "reviewed_by_human": False,
            "safety_gate_passed": False,
            "no_known_toxicity_claim": True,
        },
        "dry_lab_only_attestation": True,
        "proof_ladder_level": proof_ladder_level,
        "contact": "PLACEHOLDER — update with reviewer contact information",
        "notes": (
            "SKELETON REVIEW PACKET — generated by scripts/generate_review_packet.py. "
            "All fields are placeholders. Candidate data, benchmark results, safety "
            "attestations, and limitations must be updated before use."
        ),
    }


def validate_packet(
    packet: dict[str, Any],
    schema_path: Path,
) -> list[str]:
    """Validate a review packet dict against the E1 schema.

    Returns a list of error messages (empty if valid).
    """
    try:
        import jsonschema
    except ImportError:
        return ["jsonschema library not installed — cannot validate"]

    try:
        from openamp_foundry.utils.io import read_json
    except ImportError:
        return ["openamp_foundry package not available — cannot validate"]

    try:
        schema = read_json(schema_path)
        jsonschema.validate(instance=packet, schema=schema)
        return []
    except jsonschema.ValidationError as e:
        return [str(e)]
    except Exception as e:
        return [f"Validation error: {e}"]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate a skeleton external review packet JSON",
    )
    parser.add_argument(
        "--pipeline-version",
        required=True,
        help="Pipeline version string (e.g., v0.5.73)",
    )
    parser.add_argument(
        "--git-sha",
        required=True,
        help="Git commit SHA of the pipeline code used",
    )
    parser.add_argument(
        "--candidate-count",
        required=True,
        type=int,
        help="Expected number of candidates in the packet",
    )
    parser.add_argument(
        "--proof-ladder-level",
        required=True,
        type=int,
        choices=[1, 2, 3, 4, 5, 6, 7, 8],
        help="Highest proof-ladder level (1-8, dry-lab max 2)",
    )
    parser.add_argument(
        "--out",
        required=True,
        type=Path,
        help="Output JSON file path",
    )
    parser.add_argument(
        "--validate",
        action="store_true",
        help="Validate the generated skeleton against the E1 schema",
    )
    args = parser.parse_args(argv)

    packet = build_skeleton(
        pipeline_version=args.pipeline_version,
        git_sha=args.git_sha,
        candidate_count=args.candidate_count,
        proof_ladder_level=args.proof_ladder_level,
    )

    if args.validate:
        schema_path = Path(__file__).resolve().parent.parent / "schemas" / "external_review_packet.schema.json"
        errors = validate_packet(packet, schema_path)
        if errors:
            print("VALIDATION FAILED:", file=sys.stderr)
            for err in errors:
                print(f"  - {err}", file=sys.stderr)
            # Still write the output for inspection
        else:
            print("Validation passed: skeleton is schema-valid.")

    args.out.write_text(json.dumps(packet, indent=2, ensure_ascii=False))
    print(f"Wrote skeleton review packet to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
