"""SBW- Synthetic Boundary Warning schema.

Machine-checkable label enforcement for synthetic lab results.
Prevents synthetic data from being treated as experimental validation.
Verdict: labelled / partially_labelled / unlabelled.
"""

from __future__ import annotations

from dataclasses import dataclass, field

VALID_SBW_DATA_TYPES: frozenset[str] = frozenset({
    "mic_simulation",
    "structure_prediction",
    "docking_score",
    "md_trajectory",
    "hemolysis_simulation",
    "toxicity_simulation",
    "embedding_vector",
    "activity_score",
})

VALID_SBW_VERDICTS: frozenset[str] = frozenset({
    "labelled",
    "partially_labelled",
    "unlabelled",
})

SYNTHETIC_LABEL_REQUIRED: bool = True
CANNOT_SUPPORT_BIOLOGICAL_CLAIM: bool = True

WARNING_TEXT: str = (
    "SYNTHETIC DATA: This output was generated by computational simulation. "
    "It cannot substitute for experimental wet-lab validation and must not be "
    "interpreted as biological proof of antimicrobial activity."
)


@dataclass
class SyntheticDataRecord:
    record_id: str
    data_type: str
    source_model: str
    synthetic_label: bool
    warning_attached: bool
    is_compliant: bool = False


@dataclass
class SyntheticBoundaryWarning:
    sbw_id: str
    pipeline_version: str
    artifact_id: str
    synthetic_records: list[SyntheticDataRecord]
    n_records: int = 0
    n_labelled: int = 0
    n_unlabelled: int = 0
    unlabelled_ids: list[str] = field(default_factory=list)
    verdict: str = "unlabelled"
    cannot_support_biological_claim: bool = True
    dry_lab_only: bool = True
    limitations: list[str] = field(default_factory=list)
    created_at: str = ""


def _compute_verdict(n_records: int, n_labelled: int, n_unlabelled: int) -> str:
    if n_records == 0 or n_labelled == 0:
        return "unlabelled"
    if n_labelled == n_records:
        return "labelled"
    return "partially_labelled"


def build_synthetic_boundary_warning(
    *,
    sbw_id: str,
    pipeline_version: str,
    artifact_id: str,
    synthetic_records: list[dict],
    limitations: list[str],
    created_at: str,
) -> SyntheticBoundaryWarning:
    records: list[SyntheticDataRecord] = []
    for sr in synthetic_records:
        is_compliant = sr.get("synthetic_label", False) and sr.get("warning_attached", False)
        records.append(SyntheticDataRecord(
            record_id=sr["record_id"],
            data_type=sr["data_type"],
            source_model=sr["source_model"],
            synthetic_label=sr.get("synthetic_label", False),
            warning_attached=sr.get("warning_attached", False),
            is_compliant=is_compliant,
        ))
    n_records = len(records)
    n_labelled = sum(1 for r in records if r.is_compliant)
    n_unlabelled = n_records - n_labelled
    unlabelled_ids = [r.record_id for r in records if not r.is_compliant]
    verdict = _compute_verdict(n_records, n_labelled, n_unlabelled)
    sbw = SyntheticBoundaryWarning(
        sbw_id=sbw_id,
        pipeline_version=pipeline_version,
        artifact_id=artifact_id,
        synthetic_records=records,
        n_records=n_records,
        n_labelled=n_labelled,
        n_unlabelled=n_unlabelled,
        unlabelled_ids=unlabelled_ids,
        verdict=verdict,
        cannot_support_biological_claim=True,
        dry_lab_only=True,
        limitations=limitations,
        created_at=created_at,
    )
    validate_synthetic_boundary_warning(sbw)
    return sbw


def validate_synthetic_boundary_warning(
    sbw: SyntheticBoundaryWarning,
) -> None:
    if not sbw.sbw_id.startswith("SBW-"):
        raise ValueError(f"sbw_id must start with 'SBW-': {sbw.sbw_id!r}")
    if not sbw.pipeline_version:
        raise ValueError("pipeline_version must be non-empty")
    if not sbw.artifact_id:
        raise ValueError("artifact_id must be non-empty")
    for i, rec in enumerate(sbw.synthetic_records):
        if not rec.record_id:
            raise ValueError(
                f"synthetic_records[{i}].record_id must be non-empty"
            )
        if rec.data_type not in VALID_SBW_DATA_TYPES:
            raise ValueError(
                f"synthetic_records[{i}].data_type {rec.data_type!r} "
                f"not in VALID_SBW_DATA_TYPES"
            )
        if not rec.source_model:
            raise ValueError(
                f"synthetic_records[{i}].source_model must be non-empty"
            )
        expected_compliant = rec.synthetic_label and rec.warning_attached
        if rec.is_compliant != expected_compliant:
            raise ValueError(
                f"synthetic_records[{i}].is_compliant {rec.is_compliant} != "
                f"{expected_compliant} (expected from synthetic_label={rec.synthetic_label}, "
                f"warning_attached={rec.warning_attached})"
            )
    expected_n_records = len(sbw.synthetic_records)
    if sbw.n_records != expected_n_records:
        raise ValueError(
            f"n_records {sbw.n_records} != {expected_n_records} "
            f"(len(synthetic_records))"
        )
    expected_n_labelled = sum(1 for r in sbw.synthetic_records if r.is_compliant)
    if sbw.n_labelled != expected_n_labelled:
        raise ValueError(
            f"n_labelled {sbw.n_labelled} != {expected_n_labelled}"
        )
    expected_n_unlabelled = len(sbw.synthetic_records) - expected_n_labelled
    if sbw.n_unlabelled != expected_n_unlabelled:
        raise ValueError(
            f"n_unlabelled {sbw.n_unlabelled} != {expected_n_unlabelled}"
        )
    expected_unlabelled_ids = [
        r.record_id for r in sbw.synthetic_records if not r.is_compliant
    ]
    if sbw.unlabelled_ids != expected_unlabelled_ids:
        raise ValueError(
            f"unlabelled_ids {sbw.unlabelled_ids} != "
            f"{expected_unlabelled_ids}"
        )
    if sbw.verdict not in VALID_SBW_VERDICTS:
        raise ValueError(
            f"verdict {sbw.verdict!r} not in VALID_SBW_VERDICTS"
        )
    expected_verdict = _compute_verdict(
        sbw.n_records, sbw.n_labelled, sbw.n_unlabelled
    )
    if sbw.verdict != expected_verdict:
        raise ValueError(
            f"verdict {sbw.verdict!r} inconsistent with "
            f"n_records={sbw.n_records}, n_labelled={sbw.n_labelled}, "
            f"n_unlabelled={sbw.n_unlabelled}"
        )
    if sbw.cannot_support_biological_claim is not True:
        raise ValueError("cannot_support_biological_claim must be True")
    if sbw.dry_lab_only is not True:
        raise ValueError("dry_lab_only must be True")
    if not sbw.limitations:
        raise ValueError("limitations must be non-empty")
    if not sbw.created_at:
        raise ValueError("created_at must be non-empty")


def format_synthetic_boundary_warning(
    sbw: SyntheticBoundaryWarning,
) -> str:
    lines = [
        f"Synthetic Boundary Warning — {sbw.sbw_id}",
        f"Pipeline: {sbw.pipeline_version}",
        f"Artifact: {sbw.artifact_id}",
        f"Verdict: {sbw.verdict}",
        f"Records: {sbw.n_labelled}/{sbw.n_records} labelled",
    ]
    if sbw.unlabelled_ids:
        lines.append(
            f"Unlabelled: {', '.join(sbw.unlabelled_ids)}"
        )
    lines.append("Synthetic records:")
    for rec in sbw.synthetic_records:
        status = "COMPLIANT" if rec.is_compliant else "NON-COMPLIANT"
        lines.append(
            f"  [{status}] {rec.record_id}: {rec.data_type} "
            f"({rec.source_model})"
        )
    lines.append("")
    lines.append(WARNING_TEXT)
    if sbw.limitations:
        lines.append(f"Limitations: {'; '.join(sbw.limitations)}")
    lines.append(f"Created: {sbw.created_at}")
    lines.append(f"dry_lab_only: {sbw.dry_lab_only}")
    lines.append(f"cannot_support_biological_claim: {sbw.cannot_support_biological_claim}")
    return "\n".join(lines)
